### ISSUE TITLE
Get all modelRuntimes by model id

### ISSUE THREAD

**Issue by esmeneev** [Hydrospheredata/hydro-serving#11]
Right now we can get modelRuntimes for a given model using `/api/v1/modelRuntime/{modelId}/last` endpoint, but it's limited by a required 'maximum' query parameter, and we don't know how many modelRuntimes exist for this model, so we can't set maximum. 
We need to either add some kind of pagination to this endpoint, or create a new endpoint that will return all modelRuntimes for a given model.

**Comment by KineticCookie** [comment]
Closed since API is changed.
