### ISSUE TITLE
Does it support cassandra?

### ISSUE THREAD

**Issue by AbhayAg** [Hydrospheredata/hydro-serving#147]
Does it support cassandra?

@AbhayAg I've removed template text from your message

**Comment by Zajs** [comment]
Hi @AbhayAg,
For what purposes do you want to use Cassandra?
 - as model storage?
 - as metadata storage instead of Potgresql?

**Comment by AbhayAg** [comment]
For data storing and making data storage fault tolerant.

**Comment by Zajs** [comment]
Now we store next things:
 - serialized models - we use Amazon S3 or local file system (HDFS in future releases)
 - metadata for models (contracts, build history, versions links) - we use PostgreSQL
 - system and model performance metrics - we use InfluxDF/Elasticsearch/Prometheus

Can you clarify which kind of data you want to store in Cassandra?

**Comment by AbhayAg** [comment]
I will be using Cassandra for storing transactions data which I can't
afford to loose at any cost. and one more thing I was trying to install hs
for serving cli but it is not there. How can I deploy my model?

**Comment by KineticCookie** [comment]
Hello @AbhayAg 
> and one more thing I was trying to install hs for serving cli but it is not there

What version of python do you use? Did you use `pip install hs`?

> How can I deploy my model?

Basically it's just `cd model_folder && hs upload --host $HOST -- port $PORT`
But you need to fill some metadata first. [Here](https://github.com/Hydrospheredata/hydro-serving-cli) you can find detailed information. 
[Here](https://github.com/Hydrospheredata/hydro-serving-example/tree/master/stateful_lstm_example/pipeline) you can find 3 example models with filled metadata.

**Comment by AbhayAg** [comment]
Does it work with python 3.0. Because I am using it with python 2.0

**Comment by KineticCookie** [comment]
@AbhayAg Yes, python3 is the one you need.

**Comment by AbhayAg** [comment]
Ok. I will try that. Thanks man.

**Comment by Zajs** [comment]
@AbhayAg 
Are you going to store each request and response to your models?

**Comment by AbhayAg** [comment]
Yeah in some situations I may store that too. But my main reason behind
using that is I want my data to be safe and always available. So I cannt
move on from Cassandra. Do you have connector for that?

**Comment by Zajs** [comment]
Right now we don't have a connector to Cassandra.

**Comment by AbhayAg** [comment]
Are you guys planning to build one for Cassandra? Because I think cassandra
is getting more and more traction. May be you can guide me how to write
connector for cassandra?

**Comment by Zajs** [comment]
Yes, we are planning to build a connector for Cassandra, also we are going to create seed project for integration with SMACK stack. 

If you want to create the connector for Cassandra you will have to implement [*Repository](https://github.com/Hydrospheredata/hydro-serving/tree/master/manager/src/main/scala/io/hydrosphere/serving/manager/repository) interfaces.

**Comment by AbhayAg** [comment]
I have only 1.5 years of experience . So, I think I will be needed more
help. Can you start the initial structure and then I can contribute in
that. Then you can test it. Is it possible?

**Comment by AbhayAg** [comment]
Hey
By the way I am also getting some issue while running docker-compose. Can
you please check once.
error is :-

prometheus       | time="2018-05-08T08:21:05Z" level=error msg="Error
reading file "/var/targets/allServices.json": invalid character 'o' in
literal null (expecting 'u')" source="file.go:199"

Revert me asap.

**Comment by KineticCookie** [comment]
@AbhayAg could you please create a new issue and fill more information about docker-compose?
1. what docker compose file do you use?
2. what environment variables did you set prior to launching compose
3. did you try to `docker-compose pull` before launch?

**Comment by AbhayAg** [comment]
Yeah It worked. Thanks man.

**Comment by AbhayAg** [comment]
Thanks Bulat.
It worked. But I am finding it little hassled as every time I change my
docker it stops working and It created rigid coupling between docker and
docker-compose. So, can you suggest something for that?
