### ISSUE TITLE
Hydro Serving supports the Cloudera CDH

### ISSUE THREAD

**Issue by nellaivijay** [Hydrospheredata/hydro-serving#15]
Team, 
Deos the Hydro Serving supports the Cloudera CDH?

Thanks
Vijay

**Comment by spushkarev** [comment]
@nellaivijay there no out of the box parcel for CDH right now. 
But we are collaborating with Cloudera folks. So, your input is really appreciated.
Are you interested in integration with Datascience Workbench?
