### ISSUE TITLE
managerui exited with code 1

### ISSUE THREAD

**Issue by mullerhai** [Hydrospheredata/hydro-serving#188]
manager      | APP_OPTS=-Dapplication.grpcPort=9091 -Dapplication.port=9090 -DopenTracing.zipkin.enabled=false -DopenTracing.zipkin.port=9411 -DopenTracing.zipkin.host=zipkin -Dmanager.advertisedHost=manager -Dmanager.advertisedPort=9091 -Ddatabase.jdbcUrl=jdbc:postgresql://postgres:5432/docker -Ddatabase.username=docker -Ddatabase.password=docker -DcloudDriver.docker.networkName=demo_hydronet -DdockerRepository.type=local -Dapplication.shadowingOn=false -Dsidecar.adminPort=8082 -Dsidecar.ingressPort=8080 -Dsidecar.egressPort=8081 -Dsidecar.host=sidecar
postgres     | LOG:  database system is ready to accept connections
postgres     | LOG:  autovacuum launcher started
sidecar      | [2018-07-26 08:52:31.494][1][info][main] source/server/server.cc:178] initializing epoch 0 (hot restart version=9.200.16384.227.options=capacity=16384, num_slots=8209 hash=228984379728933363)
manager      | Archive:  /hydro-serving/app/lib/jffi-1.2.9-native.jar
sidecar      | [2018-07-26 08:52:31.532][1][warning][upstream] source/common/config/grpc_mux_impl.cc:205] gRPC config stream closed: 1, 
sidecar      | [2018-07-26 08:52:31.532][1][warning][upstream] source/common/config/grpc_mux_impl.cc:36] Unable to establish new stream
sidecar      | [2018-07-26 08:52:31.532][1][info][config] source/server/configuration_impl.cc:52] loading 0 listener(s)
sidecar      | [2018-07-26 08:52:31.532][1][info][config] source/server/configuration_impl.cc:92] loading tracing configuration
sidecar      | [2018-07-26 08:52:31.532][1][info][config] source/server/configuration_impl.cc:119] loading stats sink configuration
sidecar      | [2018-07-26 08:52:31.533][1][info][main] source/server/server.cc:353] starting main dispatch loop
sidecar      | [2018-07-26 08:52:31.536][1][info][upstream] source/common/upstream/cluster_manager_impl.cc:127] cm init: initializing cds
manager      |    creating: jni/x86_64-Linux/
manager      |   inflating: jni/x86_64-Linux/libjffi-1.2.so
managerui    | rm: can't remove '/etc/nginx/conf.d/default.conf': No such file or directory
managerui exited with code 1

**Comment by KineticCookie** [comment]
closed since fixed in ui repo
