### ISSUE TITLE
grpc issue when exec "docker-compose up"

### ISSUE THREAD

**Issue by polarBearGit** [Hydrospheredata/hydro-serving#189]
hello , I get a issue when exec "docker-compose up" on manager project, can you have a look, thanks very much

the logs as follow:

source/common/upstream/cluster_manager_impl.cc:388] add/update cluster manager-http starting warming
manager      | [2018-07-27 08:14:10.570][ERROR] a.a.OneForOneStrategy a.e.s.Slf4jLogger$$anonfun$receive$1.$anonfun$applyOrElse$1.69 null
manager      | java.lang.NullPointerException: null
manager      | 	at com.google.protobuf.Utf8.encodedLength(Utf8.java:251) ~[protobuf-java-3.5.1.jar:?]
manager      | 	at com.google.protobuf.CodedOutputStream.computeStringSizeNoTag(CodedOutputStream.java:866) ~[protobuf-java-3.5.1.jar:?]
manager      | 	at com.google.protobuf.CodedOutputStream.computeStringSize(CodedOutputStream.java:626) ~[protobuf-java-3.5.1.jar:?]
manager      | 	at envoy.api.v2.core.SocketAddress.__computeSerializedValue(SocketAddress.scala:42) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at envoy.api.v2.core.SocketAddress.serializedSize(SocketAddress.scala:52) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at envoy.api.v2.core.Address.__computeSerializedValue(Address.scala:20) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at envoy.api.v2.core.Address.serializedSize(Address.scala:27) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at envoy.api.v2.endpoint.Endpoint.__computeSerializedValue(Endpoint.scala:18) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at envoy.api.v2.endpoint.Endpoint.serializedSize(Endpoint.scala:24) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at envoy.api.v2.endpoint.LbEndpoint.__computeSerializedValue(LbEndpoint.scala:49) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at envoy.api.v2.endpoint.LbEndpoint.serializedSize(LbEndpoint.scala:58) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at envoy.api.v2.endpoint.LocalityLbEndpoints.$anonfun$__computeSerializedValue$1(LocalityLbEndpoints.scala:57) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at envoy.api.v2.endpoint.LocalityLbEndpoints.$anonfun$__computeSerializedValue$1$adapted(LocalityLbEndpoints.scala:57) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at scala.collection.Iterator.foreach(Iterator.scala:944) ~[scala-library.jar:?]
manager      | 	at scala.collection.Iterator.foreach$(Iterator.scala:944) ~[scala-library.jar:?]
manager      | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432) ~[scala-library.jar:?]
manager      | 	at scala.collection.IterableLike.foreach(IterableLike.scala:71) ~[scala-library.jar:?]
manager      | 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70) ~[scala-library.jar:?]
manager      | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[scala-library.jar:?]
manager      | 	at envoy.api.v2.endpoint.LocalityLbEndpoints.__computeSerializedValue(LocalityLbEndpoints.scala:57) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at envoy.api.v2.endpoint.LocalityLbEndpoints.serializedSize(LocalityLbEndpoints.scala:65) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at envoy.api.v2.ClusterLoadAssignment.$anonfun$__computeSerializedValue$1(ClusterLoadAssignment.scala:38) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at envoy.api.v2.ClusterLoadAssignment.$anonfun$__computeSerializedValue$1$adapted(ClusterLoadAssignment.scala:38) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at scala.collection.immutable.List.foreach(List.scala:389) ~[scala-library.jar:?]
manager      | 	at envoy.api.v2.ClusterLoadAssignment.__computeSerializedValue(ClusterLoadAssignment.scala:38) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at envoy.api.v2.ClusterLoadAssignment.serializedSize(ClusterLoadAssignment.scala:45) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at scalapb.GeneratedMessage.toByteString(GeneratedMessageCompanion.scala:140) ~[scalapb-runtime_2.12-0.7.4.jar:0.7.4]
manager      | 	at scalapb.GeneratedMessage.toByteString$(GeneratedMessageCompanion.scala:139) ~[scalapb-runtime_2.12-0.7.4.jar:0.7.4]
manager      | 	at envoy.api.v2.ClusterLoadAssignment.toByteString(ClusterLoadAssignment.scala:28) ~[envoy-data-plane-api_2.12-v1.6.0_1.jar:v1.6.0_1]
manager      | 	at scalapb.AnyCompanionMethods.pack(AnyMethods.scala:35) ~[scalapb-runtime_2.12-0.7.4.jar:0.7.4]
manager      | 	at scalapb.AnyCompanionMethods.pack$(AnyMethods.scala:30) ~[scalapb-runtime_2.12-0.7.4.jar:0.7.4]
manager      | 	at com.google.protobuf.any.Any$.pack(Any.scala:183) ~[scalapb-runtime_2.12-0.7.4.jar:0.7.4]
manager      | 	at scalapb.AnyCompanionMethods.pack(AnyMethods.scala:28) ~[scalapb-runtime_2.12-0.7.4.jar:0.7.4]
manager      | 	at scalapb.AnyCompanionMethods.pack$(AnyMethods.scala:27) ~[scalapb-runtime_2.12-0.7.4.jar:0.7.4]
manager      | 	at com.google.protobuf.any.Any$.pack(Any.scala:183) ~[scalapb-runtime_2.12-0.7.4.jar:0.7.4]
manager      | 	at ### **### io.hydrosphere.serving.manager.service.envoy.xds.AbstractDSActor.$anonfun$sendToObserver$1(AbstractDSActor.scala:63) ~[manager.jar:0.0.24-SNAPSHOT]**
manager      | 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234) ~[scala-library.jar:?]
manager      | 	at scala.collection.immutable.List.foreach(List.scala:389) ~[scala-library.jar:?]
manager      | 	at scala.collection.TraversableLike.map(TraversableLike.scala:234) ~[scala-library.jar:?]
manager      | 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227) ~[scala-library.jar:?]
manager      | 	at scala.collection.immutable.List.map(List.scala:295) ~[scala-library.jar:?]
manager      | 	at **io.hydrosphere.serving.manager.service.envoy.xds.AbstractDSActor.io$hydrosphere$serving$manager$service$envoy$xds$AbstractDSActor$$sendToObserver(AbstractDSActor.scala:63) ~[manager.jar:0.0.24-SNAPSHOT]
manager      | 	at io.hydrosphere.serving.manager.service.envoy.xds.AbstractDSActor$$anonfun$receive$1.applyOrElse(AbstractDSActor.scala:90) ~[manager.jar:0.0.24-SNAPSHOT]**

**Comment by KineticCookie** [comment]
Hello @polarBearGit 
Looks like you deployed an unstable snapshot build.
Last stable versions are defined in https://github.com/Hydrospheredata/hydro-serving/blob/master/docker-compose.yml
i.e. for manager it's 0.0.20

**Comment by KineticCookie** [comment]
closed since image version is old
