### ISSUE TITLE
Docker doesn't remove containers after application's update

### ISSUE THREAD

**Issue by tidylobster** [Hydrospheredata/hydro-serving#202]
After one of the models in the application gets updated, its container doesn't get removed as was before. Instead a new container gets created and the whole environment would quickly ran out of resources. 

![image](https://user-images.githubusercontent.com/7824882/45027857-559a2000-b04b-11e8-9bd2-1b06a9b832d4.png)

**Comment by KineticCookie** [comment]
The same behavior is observed when user deletes an application.
