### ISSUE TITLE
Docker builds images even on unsuccessful pip installation

### ISSUE THREAD

**Issue by tidylobster** [Hydrospheredata/hydro-serving#215]
```RUN ls /model/files/requirements.txt && pip install -r /model/files/requirements.txt --target /model/lib || echo "no requirements"```

Try to create an empty `requirements.txt` one step before installing it with pip.

**Comment by KineticCookie** [comment]
Need to modify the BuildScript for python models.

**Comment by KineticCookie** [comment]
Waiting for @tidylobster's bug reproduction

**Comment by KineticCookie** [comment]
#219 provides a safer pip build script.
