### ISSUE TITLE
status: 500, error: InternalUncaught, message: UNKNOWN: Exception calling application: unsupported operand type(s) for *: 'TensorProto' and 'TensorProto'

### ISSUE THREAD

**Issue by ravimadhusudhan8** [Hydrospheredata/hydro-serving#221]
Created a Model -that was a simple calculator service - with standard add, subtract, multiply ... that take 2 parameters and output a single scalar.

The Model uploaded fine - no issues [the earlier suggestion helped].

Created an Application.

> On testing the Application - got the error  - status: 500, error: InternalUncaught, message: UNKNOWN: Exception calling application: unsupported operand type(s) for *: 'TensorProto' and 'TensorProto'

Attached screenshots - 

![simple-add](https://user-images.githubusercontent.com/45240898/50312658-10bdbc00-0477-11e9-8b8f-ec2b2255bf83.PNG)

![calculator-service](https://user-images.githubusercontent.com/45240898/50312675-203d0500-0477-11e9-9cb3-7d8cc9463dfa.PNG)

**Comment by ravimadhusudhan8** [comment]
Got it!

Thanks

**Comment by ravimadhusudhan8** [comment]
Changed the code to this - based on **func_main.py** at 
hydro-serving-example/demos/stateful_lstm_example/pipeline/postprocessing/src

And using TensorProto objects as input and output as suggested. Attached are the docker logs and test app screenshots.

Thanks
--------------------------------------------------------------------------------
import math
import hydro_serving_grpc as hs

# Function to multiply two numbers
def multiply(x, y):
    input_x = x.double_val
    input_y = y.double_val
    print(input_x, input_y)
    result = input_x * input_y
    tensor_result_output = hs.TensorProto(
        dtype=hs.DT_DOUBLE,
        double_val=result
    )
    return tensor_result_output

----------------------------------------------------------------

Got this error message - status: 500, error: InternalUncaught, message: UNKNOWN: Exception calling application: unsupported operand type(s) for *: 'google.protobuf.pyext._message.RepeatedScalarContainer' and 'google.protobuf.pyext._message.RepeatedScalarContainer'
![multiply](https://user-images.githubusercontent.com/45240898/50456038-a5b13100-091f-11e9-9765-611262e0f599.PNG)

 
![docker-logs](https://user-images.githubusercontent.com/45240898/50456200-d6de3100-0920-11e9-944d-fa454d1796f1.PNG)

**Comment by tidylobster** [comment]
Still, you're operating on the object, that doesn't support `*` operand. This time it's a protobuf's `RepeatedScalarContainer` object, which is similar to list. In your case those would be a lists of length 1. So, the correct steps would be: 
```python 
...
result = input_x[0] * input_y[0]
tensor_result_output = hs.TensorProto(
    dtype=hs.DT_DOUBLE,
    double_val=[result]
)
...
```

Note, that I've made a list from `result` and passed it to `double_val` key in the response tensor constructor. For future reference, the [documentation for the python bindings to protocol buffers](https://developers.google.com/protocol-buffers/docs/reference/python-generated) explains this and other issues.

**Comment by ravimadhusudhan8** [comment]
Thanks for the link and suggestions.

Getting a different error with the changed code 

---------------------------------------------------
import math
import hydro_serving_grpc as hs
# Function to subtract two numbers
def subtract(x, y):
    input_x = x.double_val
    input_y = y.double_val
    print(input_x[0], input_y[0])
    result = input_x[0] - input_y[0]
    tensor_result_output = hs.TensorProto(
        dtype=hs.DT_DOUBLE,
        double_val=[result]
    )
    return tensor_result_output
 -------------------------------------------------------
![subtract](https://user-images.githubusercontent.com/45240898/50458514-a81c8680-0931-11e9-8aed-152fca783755.PNG)
![docker-logs-2](https://user-images.githubusercontent.com/45240898/50458516-abb00d80-0931-11e9-9013-3399548f9495.PNG)

**Comment by ravimadhusudhan8** [comment]
Great that worked!
You have been very responsive!
Thanks!
