### ISSUE TITLE
returning a binary object

### ISSUE THREAD

**Issue by ravimadhusudhan8** [Hydrospheredata/hydro-serving#223]
There was a page with descriptions - table - of shape [scalar etc ..] and types [DT_String etc ..] that go into serving.yaml and the code - I don't see it now as part of the documentation. 

Please send me a link. 

Thanks

**Comment by tidylobster** [comment]
Thank you for mentioning that. I've returned the page and moved it to a different "Reference" category. You can find all possible contract values here - https://hydrosphere.io/serving-docs/manifests.html. Manifest structure is declared here - https://hydrosphere.io/serving-docs/write-manifests.html#kind-model
