### ISSUE TITLE
Tensorflow 1.12 model LookupTable initialization error

### ISSUE THREAD

**Issue by ravimadhusudhan8** [Hydrospheredata/hydro-serving#227]
Applying application.yaml ...
{'kafkaStreaming': [], 'executionGraph': {'stages': [{'services': [{'weight': 100, 'signatureName': 'signature-to-be-ignored', 'runtimeId': 6, 'modelVersionId': 17}]}]}, 'name': 'seq2seq-service'}
Server app response
{'name': 'seq2seq-service', 'kafkaStreaming': [], 'id': 9, 'executionGraph': {'stages': [{'services': [{'runtime': {'name': 'hydrosphere/serving-runtime-tensorflow', 'tags': ['tensorflow'], 'version': '1.7.0-latest', 'id': 6, 'configParams': {}, 'suitableModelType': ['tensorflow:1.7.0']}, 'modelVersion': {'model': {'name': 'seq2seq', 'modelContract': 'model_name: "seq2seq"\nsignatures {\n  signature_name: "serving_default"\n  inputs {\n    name: "input_data"\n    shape {\n      dim {\n        size: -1\n        name: ""\n      }\n      dim {\n        size: 1\n        name: ""\n      }\n      unknown_rank: false\n    }\n    dtype: DT_STRING\n  }\n  outputs {\n    name: "output"\n    shape {\n      dim {\n        size: -1\n        name: ""\n      }\n      dim {\n        size: 1\n        name: ""\n      }\n      unknown_rank: false\n    }\n    dtype: DT_STRING\n  }\n}\n', 'modelType': 'tensorflow:1.12.0', 'id': 12, 'updated': '2019-01-08T23:18:20.951', 'created': '2019-01-08T21:04:12.152'}, 'modelContract': 'model_name: "seq2seq"\nsignatures {\n  signature_name: "serving_default"\n  inputs {\n    name: "input_data"\n    shape {\n      dim {\n        size: -1\n        name: ""\n      }\n      dim {\n        size: 1\n        name: ""\n      }\n      unknown_rank: false\n    }\n    dtype: DT_STRING\n  }\n  outputs {\n    name: "output"\n    shape {\n      dim {\n        size: -1\n        name: ""\n      }\n      dim {\n        size: 1\n        name: ""\n      }\n      unknown_rank: false\n    }\n    dtype: DT_STRING\n  }\n}\n', 'imageName': 'seq2seq', 'imageTag': '3', 'modelName': 'seq2seq', 'modelType': 'tensorflow:1.12.0', 'id': 17, 'imageSHA256': 'eaff8f33c808469a48c98fc83a4b0971bff945f9ed0811e2b226119bc0a631e4', 'modelVersion': 3, 'created': '2019-01-08T23:18:23.041'}, 'environment': {'id': 0, 'name': 'Without Env', 'placeholders': []}, 'weight': 100}], 'dataProfileFields': {}}]}, 'contract': 'model_name: "seq2seq"\nsignatures {\n  signature_name: "serving_default"\n  inputs {\n    name: "input_data"\n    shape {\n      dim {\n        size: -1\n        name: ""\n      }\n      dim {\n        size: 1\n        name: ""\n      }\n      unknown_rank: false\n    }\n    dtype: DT_STRING\n  }\n  outputs {\n    name: "output"\n    shape {\n      dim {\n        size: -1\n        name: ""\n      }\n      dim {\n        size: 1\n        name: ""\n      }\n      unknown_rank: false\n    }\n    dtype: DT_STRING\n  }\n}\n'}
{'application.yaml': [{'contract': 'model_name: "seq2seq"\n'
                                   'signatures {\n'
                                   '  signature_name: "serving_default"\n'
                                   '  inputs {\n'
                                   '    name: "input_data"\n'
                                   '    shape {\n'
                                   '      dim {\n'
                                   '        size: -1\n'
                                   '        name: ""\n'
                                   '      }\n'
                                   '      dim {\n'
                                   '        size: 1\n'
                                   '        name: ""\n'
                                   '      }\n'
                                   '      unknown_rank: false\n'
                                   '    }\n'
                                   '    dtype: DT_STRING\n'
                                   '  }\n'
                                   '  outputs {\n'
                                   '    name: "output"\n'
                                   '    shape {\n'
                                   '      dim {\n'
                                   '        size: -1\n'
                                   '        name: ""\n'
                                   '      }\n'
                                   '      dim {\n'
                                   '        size: 1\n'
                                   '        name: ""\n'
                                   '      }\n'
                                   '      unknown_rank: false\n'
                                   '    }\n'
                                   '    dtype: DT_STRING\n'
                                   '  }\n'
                                   '}\n',
                       'executionGraph': {'stages': [{'dataProfileFields': {},
                                                      'services': [{'environment': {'id': 0,
                                                                                    'name': 'Without '
                                                                                            'Env',
                                                                                    'placeholders': []},
                                                                    'modelVersion': {'created': '2019-01-08T23:18:23.041',
                                                                                     'id': 17,
                                                                                     'imageName': 'seq2seq',
                                                                                     'imageSHA256': 'eaff8f33c808469a48c98fc83a4b0971bff945f9ed0811e2b226119bc0a631e4',
                                                                                     'imageTag': '3',
                                                                                     'model': {'created': '2019-01-08T21:04:12.152',
                                                                                               'id': 12,
                                                                                               'modelContract': 'model_name: '
                                                                                                                '"seq2seq"\n'
                                                                                                                'signatures '
                                                                                                                '{\n'
                                                                                                                '  '
                                                                                                                'signature_name: '
                                                                                                                '"serving_default"\n'
                                                                                                                '  '
                                                                                                                'inputs '
                                                                                                                '{\n'
                                                                                                                '    '
                                                                                                                'name: '
                                                                                                                '"input_data"\n'
                                                                                                                '    '
                                                                                                                'shape '
                                                                                                                '{\n'
                                                                                                                '      '
                                                                                                                'dim '
                                                                                                                '{\n'
                                                                                                                '        '
                                                                                                                'size: '
                                                                                                                '-1\n'
                                                                                                                '        '
                                                                                                                'name: '
                                                                                                                '""\n'
                                                                                                                '      '
                                                                                                                '}\n'
                                                                                                                '      '
                                                                                                                'dim '
                                                                                                                '{\n'
                                                                                                                '        '
                                                                                                                'size: '
                                                                                                                '1\n'
                                                                                                                '        '
                                                                                                                'name: '
                                                                                                                '""\n'
                                                                                                                '      '
                                                                                                                '}\n'
                                                                                                                '      '
                                                                                                                'unknown_rank: '
                                                                                                                'false\n'
                                                                                                                '    '
                                                                                                                '}\n'
                                                                                                                '    '
                                                                                                                'dtype: '
                                                                                                                'DT_STRING\n'
                                                                                                                '  '
                                                                                                                '}\n'
                                                                                                                '  '
                                                                                                                'outputs '
                                                                                                                '{\n'
                                                                                                                '    '
                                                                                                                'name: '
                                                                                                                '"output"\n'
                                                                                                                '    '
                                                                                                                'shape '
                                                                                                                '{\n'
                                                                                                                '      '
                                                                                                                'dim '
                                                                                                                '{\n'
                                                                                                                '        '
                                                                                                                'size: '
                                                                                                                '-1\n'
                                                                                                                '        '
                                                                                                                'name: '
                                                                                                                '""\n'
                                                                                                                '      '
                                                                                                                '}\n'
                                                                                                                '      '
                                                                                                                'dim '
                                                                                                                '{\n'
                                                                                                                '        '
                                                                                                                'size: '
                                                                                                                '1\n'
                                                                                                                '        '
                                                                                                                'name: '
                                                                                                                '""\n'
                                                                                                                '      '
                                                                                                                '}\n'
                                                                                                                '      '
                                                                                                                'unknown_rank: '
                                                                                                                'false\n'
                                                                                                                '    '
                                                                                                                '}\n'
                                                                                                                '    '
                                                                                                                'dtype: '
                                                                                                                'DT_STRING\n'
                                                                                                                '  '
                                                                                                                '}\n'
                                                                                                                '}\n',
                                                                                               'modelType': 'tensorflow:1.12.0',
                                                                                               'name': 'seq2seq',
                                                                                               'updated': '2019-01-08T23:18:20.951'},
                                                                                     'modelContract': 'model_name: '
                                                                                                      '"seq2seq"\n'
                                                                                                      'signatures '
                                                                                                      '{\n'
                                                                                                      '  '
                                                                                                      'signature_name: '
                                                                                                      '"serving_default"\n'
                                                                                                      '  '
                                                                                                      'inputs '
                                                                                                      '{\n'
                                                                                                      '    '
                                                                                                      'name: '
                                                                                                      '"input_data"\n'
                                                                                                      '    '
                                                                                                      'shape '
                                                                                                      '{\n'
                                                                                                      '      '
                                                                                                      'dim '
                                                                                                      '{\n'
                                                                                                      '        '
                                                                                                      'size: '
                                                                                                      '-1\n'
                                                                                                      '        '
                                                                                                      'name: '
                                                                                                      '""\n'
                                                                                                      '      '
                                                                                                      '}\n'
                                                                                                      '      '
                                                                                                      'dim '
                                                                                                      '{\n'
                                                                                                      '        '
                                                                                                      'size: '
                                                                                                      '1\n'
                                                                                                      '        '
                                                                                                      'name: '
                                                                                                      '""\n'
                                                                                                      '      '
                                                                                                      '}\n'
                                                                                                      '      '
                                                                                                      'unknown_rank: '
                                                                                                      'false\n'
                                                                                                      '    '
                                                                                                      '}\n'
                                                                                                      '    '
                                                                                                      'dtype: '
                                                                                                      'DT_STRING\n'
                                                                                                      '  '
                                                                                                      '}\n'
                                                                                                      '  '
                                                                                                      'outputs '
                                                                                                      '{\n'
                                                                                                      '    '
                                                                                                      'name: '
                                                                                                      '"output"\n'
                                                                                                      '    '
                                                                                                      'shape '
                                                                                                      '{\n'
                                                                                                      '      '
                                                                                                      'dim '
                                                                                                      '{\n'
                                                                                                      '        '
                                                                                                      'size: '
                                                                                                      '-1\n'
                                                                                                      '        '
                                                                                                      'name: '
                                                                                                      '""\n'
                                                                                                      '      '
                                                                                                      '}\n'
                                                                                                      '      '
                                                                                                      'dim '
                                                                                                      '{\n'
                                                                                                      '        '
                                                                                                      'size: '
                                                                                                      '1\n'
                                                                                                      '        '
                                                                                                      'name: '
                                                                                                      '""\n'
                                                                                                      '      '
                                                                                                      '}\n'
                                                                                                      '      '
                                                                                                      'unknown_rank: '
                                                                                                      'false\n'
                                                                                                      '    '
                                                                                                      '}\n'
                                                                                                      '    '
                                                                                                      'dtype: '
                                                                                                      'DT_STRING\n'
                                                                                                      '  '
                                                                                                      '}\n'
                                                                                                      '}\n',
                                                                                     'modelName': 'seq2seq',
                                                                                     'modelType': 'tensorflow:1.12.0',
                                                                                     'modelVersion': 3},
                                                                    'runtime': {'configParams': {},
                                                                                'id': 6,
                                                                                'name': 'hydrosphere/serving-runtime-tensorflow',
                                                                                'suitableModelType': ['tensorflow:1.7.0'],
                                                                                'tags': ['tensorflow'],
                                                                                'version': '1.7.0-latest'},
                                                                    'weight': 100}]}]},
                       'id': 9,
                       'kafkaStreaming': [],
                       'name': 'seq2seq-service'}]}

![tensorflow-runtime-missing](https://user-images.githubusercontent.com/45240898/50866438-f0976380-1377-11e9-835a-45a78ecca601.PNG)

**Comment by KineticCookie** [comment]
Hello
This could be the result of runtime initialization failure.
Can you check the output of `docker ps -a` for any Failed or Completed containers?

**Comment by ravimadhusudhan8** [comment]
Thanks for the suggestion. 

 I have attached 3 screenshots - 

1. On creation of Application - docker ps -a -> shows TF
![tf-runtime-started](https://user-images.githubusercontent.com/45240898/51040772-59542b00-1586-11e9-929d-248b620ae30f.PNG)
 runtime created
2. Test the new Application -> error message shown
![created-app-with-seq2seq-model-makes-runtime-to-exit](https://user-images.githubusercontent.com/45240898/51040814-738e0900-1586-11e9-9426-d93bfab84f1f.PNG)

3. Again run docker ps -a -> now show that TF runtime has exited

![tf-runtime-exited](https://user-images.githubusercontent.com/45240898/51040838-8274bb80-1586-11e9-9b4d-ab2a3adacab2.PNG)

**Comment by KineticCookie** [comment]
Yeah, an error happened in the TF container. Can you provide it's logs?

**Comment by ravimadhusudhan8** [comment]
Please find the screenshots of the logs

1. Just the container name 
![docker-logs-tf-runtime](https://user-images.githubusercontent.com/45240898/51043732-6de7f180-158d-11e9-8896-adfbd163e707.PNG)
2. Logs 1
![tf-runtime-logs-1](https://user-images.githubusercontent.com/45240898/51043764-7f30fe00-158d-11e9-8a41-af749de9973b.PNG)
3. Logs 2
![tf-runtime-logs-2](https://user-images.githubusercontent.com/45240898/51043792-8fe17400-158d-11e9-89cb-62167f3e3ac4.PNG)

**Comment by KineticCookie** [comment]
🤔 seems like your model has incompatible graph nodes with tf version 1.7.0.
There is gonna be newer versions of TF runtimes soon, however I'm not sure if it will fix it.
I'll investigate this behavior.

**Comment by ravimadhusudhan8** [comment]
Thanks
