### ISSUE TITLE
restart hydro-serving after a application.conf change - 

### ISSUE THREAD

**Issue by ravimadhusudhan8** [Hydrospheredata/hydro-serving#231]
the change was to manage Streaming exception as suggested in #44 
 
What is the suggested way to restart hydro-serving - so that the uploaded models and applications are not lost?

Thanks

**Comment by KineticCookie** [comment]
Hi.
You can restart the manager container with `docker restart` command.
All required data is stored in database, thus the manager state will be safe.

**Comment by ravimadhusudhan8** [comment]
Does that apply to code change too?

**Comment by ravimadhusudhan8** [comment]
Thanks
