### ISSUE TITLE
Models to Applications mapping

### ISSUE THREAD

**Issue by ravimadhusudhan8** [Hydrospheredata/hydro-serving#239]
When a Model is used by more than one Application - will there be a separate instance of the Model for each Application ? 

_Model [M]
_Applications [A1, A2]__

M(1) -> A 1
M(2)-> A2

Is the above true?

Or is it - 

 M -> A1
 M -> A2

Thanks

ps: using the Docker - integrations install

**Comment by tidylobster** [comment]
For each application serving creates a new container with a model version. So, in your case it's the first variant.

**Comment by ravimadhusudhan8** [comment]
Thanks for the clarification!
