### ISSUE TITLE
Application response in HTML tags and not in JSON

### ISSUE THREAD

**Issue by ravimadhusudhan8** [Hydrospheredata/hydro-serving#247]
We are load testing models that we have on Hydro-serving. The numbers are great!

We are using Gatling for the tests.

When we print out the response of a HTTP request we get HTML tags...

How do we get just the JSON response we are expecting?

Here is a sample response - 

!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>HydroServingUi</title>
    <base href="/">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="./assets/images/favicon.ico">

    <link rel="apple-touch-icon" sizes="120x120" href="./assets/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="64x64" href="./assets/images/favicon-64x64.png">
    <link rel="icon" type="image/png" sizes="32x32" href="./assets/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="./assets/images/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="./assets/images/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="styles.11299a65fec21d67aee5.css"></head>
<body>
    <hydro-root></hydro-root>
<script type="text/javascript" src="runtime.ec2944dd8b20ec099bf3.js"></script><script type="text/javascript" src="polyfills.d48022d7575d7ac41b53.js"></script><script type="text/javascript" src="main.192a9dd2fa51794a197b.js"></script></body>
</html>

-----------------------------------------------------------------------------------------

Here is the input and output from Hydroserving UI - when testing the Application 
{
  "string": "foo is not a Ravi",
  "model": "foo",
  "feature": "ner"
}

Output - 
{
  "tokens": [
    "[{\"text\": \"Ravi\", \"start_char\": 11, \"end_char\": 15, \"label\": \"PERSON\"}]"
  ]
}

-----------------------------------------------------------------------------------------

Here is the cURL from Hydroserving UI -

curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "string": "foo is not a Ravi", "model": "foo", "feature": "ner" }' 'http://ec2-54-**-**-**.us-west-2.compute.amazonaws.com/gateway/applications/spacy-nlp-service-2/spacy_process'

Thanks,

Ravi

**Comment by KineticCookie** [comment]
Hi.
Servers usually return JSON response, unless there is no sidecar error.
Envoy is configured to route all requests which do not match the routing table to the UI service, and looks like this is the root of the issue.

Could you please check if `/gateway` pattern is defined in `localhost:8082/routes`.

**Comment by ravimadhusudhan8** [comment]
Please find attached the routes.txt

Here is the snippet - 

{
     "match": {
      "prefix": "/gateway"
     },
     "route": {
      "cluster": "gateway-http",
      "timeout": "69s"
     }
    }

And the routes.txt output from :8082/routes

[routes.txt](https://github.com/Hydrospheredata/hydro-serving/files/2888659/routes.txt)

**Comment by ravimadhusudhan8** [comment]
the internal network was not correct - port 80 was pointing to 9090 and not 8080 ...
