### ISSUE TITLE
call an application from within a different application

### ISSUE THREAD

**Issue by albertnanda** [Hydrospheredata/hydro-serving#250]
Hi,

How can I call an application from within a different application?
For example: Let's say I have a service called factorial(n) and I want to create a new application called calculator. How can I call factorial from the calculators func_main.py

Thanks,
AN

**Comment by albertnanda** [comment]
@tidylobster Is this possible?

**Comment by tidylobster** [comment]
No, we don't cover this particular case. You can build a multi-staged application which will pass predictions from one model to another, but you can't call other applications from it.

**Comment by albertnanda** [comment]
I manged to make it work via grpc.
