### ISSUE TITLE
Model / Application removal during runtime

### ISSUE THREAD

**Issue by ravimadhusudhan8** [Hydrospheredata/hydro-serving#251]
"Let it Crash"

Taking that paradigm to a higher level - we would like to clean up Models/Applications that fail due to SDN errors/ or other reasons and follow the Hydroserving process of hs upload and hs apply using scripts.

Are there commands like - hs -rm -m "model-name" -a "application-name"

Thanks,

Ravi

**Comment by tidylobster** [comment]
Hi, @ravimadhusudhan8 
Right now there are no such commands, but we will include this in our scope. Thank you for insights.

**Comment by KineticCookie** [comment]
I moved this feature request to specific repo: https://github.com/Hydrospheredata/hydro-serving-cli/issues/27

Thanks for the feedback!
