### ISSUE TITLE
error when running sbt manager/devRun

### ISSUE THREAD

**Issue by meittemarceline** [Hydrospheredata/hydro-serving#253]
I had this error when I run "sbt manager/devRun". I need help.

[info] [2019-03-04 18:42:12.177][INFO][main] i.h.s.m.ManagerBoot$.delayedEndpoint$io$hydrosphere$serving$manager$ManagerBoot$1.44 Using docker client config: DockerClientConfig(proxies = Map())
[info] [2019-03-04 18:42:12.194][INFO][main] c.z.h.HikariDataSource.<init>.80 HikariPool-1 - Starting...
[error] mars 04, 2019 6:42:12 PM org.postgresql.Driver connect
[error] GRAVE: Connection error: 
[error] org.postgresql.util.PSQLException: FATAL: role "docker" does not exist
[error]         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
[error]         at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2603)
[error]         at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:125)
[error]         at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:227)
[error]         at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
[error]         at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
[error]         at org.postgresql.Driver.makeConnection(Driver.java:450)
[error]         at org.postgresql.Driver.connect(Driver.java:252)
[error]         at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
[error]         at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
[error]         at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
[error]         at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
[error]         at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460)
[error]         at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534)
[error]         at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[error]         at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[error]         at io.hydrosphere.serving.manager.infrastructure.db.DatabaseService.<init>(DatabaseService.scala:9)
[error]         at io.hydrosphere.serving.manager.ManagerRepositories.<init>(ManagerRepositories.scala:12)
[error]         at io.hydrosphere.serving.manager.ManagerBoot$.delayedEndpoint$io$hydrosphere$serving$manager$ManagerBoot$1(ManagerBoot.scala:46)
[error]         at io.hydrosphere.serving.manager.ManagerBoot$delayedInit$body.apply(ManagerBoot.scala:19)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at scala.App.main(App.scala:76)
[error]         at scala.App.main$(App.scala:74)
[error]         at io.hydrosphere.serving.manager.ManagerBoot$.main(ManagerBoot.scala:19)
[error]         at io.hydrosphere.serving.manager.ManagerBoot.main(ManagerBoot.scala)
[error] mars 04, 2019 6:42:13 PM org.postgresql.Driver connect
[error] GRAVE: Connection error: 
[error] org.postgresql.util.PSQLException: FATAL: role "docker" does not exist
[error]         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
[error]         at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2603)
[error]         at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:125)

**Comment by dos65** [comment]
Have you tried to remove existing containers? 
`sbt manager/cleanDockerEnv` should help

**Comment by meittemarceline** [comment]
Thanks @dos65 for your answer. 
Yes I did it. I followed instructions in the dev guide:
`$ sbt manager/cleanDockerEnv `
`$ git clone https://github.com/Hydrospheredata/hydro-serving`
`$ sbt manager/devRun` gives this error
![image](https://user-images.githubusercontent.com/32811794/53912778-90f4c600-4051-11e9-872c-d6318ecd0962.png)
To solve this error, I changed the version of spotify docker-client from "8.8.0" to "8.12.0" and this is the new error
![image](https://user-images.githubusercontent.com/32811794/53913880-43c62380-4054-11e9-8a3f-9ea741bd9787.png)
**The version of hs (hs version 0.1.5) installed is linked to api v1 (/api/v1/model/)** 
Finally this the containers started are
![image](https://user-images.githubusercontent.com/32811794/53915371-acfb6600-4057-11e9-94ea-05a08ee7d5eb.png)

**Comment by KineticCookie** [comment]
Dev deployment changed a little bit after the release. In addition to that, please use `docker-compose` or `kubernetes` installments, since dev doesn't enable a vast majority of features
