### ISSUE TITLE
Having issues with HS upload - just pulled from the /master branch

### ISSUE THREAD

**Issue by ravimadhusudhan8** [Hydrospheredata/hydro-serving#255]
Getting this error when using a latest version of hydro-serving. 
Looks like there is an issue

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost/api/v1/model/upload

**Comment by meittemarceline** [comment]
I have the same error too. 
@ravimadhusudhan8 did you have the error describe below
[https://github.com/Hydrospheredata/hydro-serving/issues/253](url)
I need help.

**Comment by ravimadhusudhan8** [comment]
@meittemarceline I have not tried to build it

**Comment by tidylobster** [comment]
We are currently working on the major v2 release. There might be some issues, related to the API interactions, but we will resolve them as soon as possible. To fix your issues, you can install the latest cli [release candidate](https://pypi.org/project/hs/#history). 

```pip install hs==2.0.0rc2```

**Comment by ravimadhusudhan8** [comment]
Thanks for the suggestion. 
installed the version as suggested - getting this error

![hs-upload-error](https://user-images.githubusercontent.com/45240898/53984002-6d2f8f80-40e6-11e9-88ca-69ca9d4480d9.PNG)
![add-serving yaml](https://user-images.githubusercontent.com/45240898/53984012-71f44380-40e6-11e9-9519-9d2e130aadea.PNG)

**Comment by tidylobster** [comment]
Yeah, we've also made small changes to manifests. You just have to specify the runtime for the model. Something like:
```
kind: Model
runtime: "hydrosphere/serving-runtime-python:3.6-latest"
...
```

**Comment by ravimadhusudhan8** [comment]
adding runtime: "hydrosphere/serving-runtime-python:3.6-latest" to serving.yaml made it work!

![works](https://user-images.githubusercontent.com/45240898/53986591-9d7a2c80-40ec-11e9-97ba-b816dd7ace43.PNG)
