### ISSUE TITLE
apply -f "runtime.yaml" -  parser error

### ISSUE THREAD

**Issue by ravimadhusudhan8** [Hydrospheredata/hydro-serving#258]
![runtime-apply-error](https://user-images.githubusercontent.com/45240898/54052216-da5c2700-41b1-11e9-8b2b-14f55f4cc00e.PNG)

This was working with the previous version.

**Comment by ravimadhusudhan8** [comment]
:~/mlfabric/hydrosphere-python-runtimes/runtimes$ hs apply -f runtime_spacy.yaml 
Reading runtime_spacy.yaml ...
error: Error while applying: No parser found for resource kind Runtime

**Comment by PycT** [comment]
Hi Ravi,
 We are preparing the release and there are some features in rc that are undocumented yet.
 Could you please get in touch with me via email rzakiev@hydrosphere.io, let us work your case through with the team.

**Comment by ravimadhusudhan8** [comment]
Thanks Rustem!
