### ISSUE TITLE
Hydroserving documentation needs fixing - for port-forwarding 

### ISSUE THREAD

**Issue by ravimadhusudhan8** [Hydrospheredata/hydro-serving#260]
You will have to edit the documentation - to follow this command pattern that I got from -  kubectl cheat sheet

kubectl port-forward my-pod 5000:6000               # Listen on port 5000 on the local machine and forward to port 6000 on my-pod

![kubectl-port-forwarding-ports-have-to-flipped](https://user-images.githubusercontent.com/45240898/54058132-fa481680-41c2-11e9-86e4-95876df7b825.PNG)

**Comment by tidylobster** [comment]
Thank you for pointing that out. I'll fix that.

**Comment by ravimadhusudhan8** [comment]
@tidylobster You are welcome.
