### ISSUE TITLE
New K8 install does not have sidecar

### ISSUE THREAD

**Issue by ravimadhusudhan8** [Hydrospheredata/hydro-serving#265]
There does not seem to be a sidecar with a K8 install that I did with -

$ helm install --name serving hydrosphere/serving

From this page - https://hydrosphere.io/serving-docs/installation.html

![no-sidecar](https://user-images.githubusercontent.com/45240898/55354936-eecfce80-5494-11e9-80bc-a7404666e33b.PNG)

**Comment by ravimadhusudhan8** [comment]
I have installed an older version - 

 helm install --name my-release https://github.com/Hydrospheredata/hydro-serving-helm/releases/download/0.1.15/serving-0.1.15.tgz

Which works on another cluster - and sidecar comes up.

**Comment by KineticCookie** [comment]
Yeah, we got rid of the sidecar in the new version.
We will make an announcement for the release

**Comment by ravimadhusudhan8** [comment]
Thanks @KineticCookie for the update
