### ISSUE TITLE
HS upload fails on - one cluster - but works on another cluster! Same versions of Helm charts and HS!!

### ISSUE THREAD

**Issue by ravimadhusudhan8** [Hydrospheredata/hydro-serving#266]
HS upload fails on - one K8 cluster - but works on another K8 cluster! 
Both installs have same versions of Helm charts and HS !

Trying to work with a stable release - so using the versions that work at least on one cluster - these versions work on one cluster.

$Helm list -
my-release	1       	Mon Apr  1 19:58:51 2019	DEPLOYED	serving-0.1.15	           	default  

$hs --version
hs version 2.0.0rc3

And  serving.yaml and  src/func_main.py are identical on both clusters

**serving.yaml -** 

kind: Model
name: "add-service"
runtime: "hydrosphere/serving-runtime-python:3.6-latest"
model-type: "python:3.6"
payload:
  - "src/"
contract:
  add:
    inputs:
      x:
        shape: scalar
        type: double
      y:
        shape: scalar
        type: double
    outputs:
      z:
        shape: scalar
        type: double

**src/func_main.py** 

import math
import hydro_serving_grpc as hs

# Function to add two numbers

def add(x, y):
    input_x = x.double_val
    input_y = y.double_val
    print(input_x[0], input_y[0])
    result = input_x[0] + input_y[0]
    tensor_result_output = hs.TensorProto(
        dtype=hs.DT_DOUBLE,
        double_val=[result]
    )
    return hs.PredictResponse(
        outputs={
            "result": tensor_result_output
        }
    )

![hs_upload_fails](https://user-images.githubusercontent.com/45240898/55359836-d4035700-54a0-11e9-914d-4864218dfd95.PNG)

**Comment by KineticCookie** [comment]
Hi!
Seems like you got different versions of serving cluster.
We already released a stable version. Feel free to check docs for the new updates!

**Comment by ravimadhusudhan8** [comment]
Thanks @KineticCookie .

Have started using Version 2.0. 

Everything that we need worked fine!
