### ISSUE TITLE
Sample generation

### ISSUE THREAD

**Issue by KirilIakovliev** [Hydrospheredata/hydro-serving#300]
There is a problem when you are trying to make a test of face recognition pipeline. Specifically it cannot generate a sample with appropriate dimensions. 

<img width="1108" alt="Screenshot 2019-09-25 at 15 42 05" src="https://user-images.githubusercontent.com/31926158/65601663-21253900-dfab-11e9-8427-c677244472a0.png">

**Comment by archichen** [comment]
Same problem. Have you resolved this problem?

**Comment by archichen** [comment]
> Same problem. Have you resolved this problem?

But it occurred when I upload my deep learning model.

**Comment by KineticCookie** [comment]
Hey @archichen 
Seem like manager service cannot construct an example data for your model's contract/signature.

Could you please send the model signature? (It can be found in the UI in model details)
