### ISSUE TITLE
Ping error: UNIMPLEMENTED: Method not found!

### ISSUE THREAD

**Issue by archichen** [Hydrospheredata/hydro-serving#318]
## Error detail

Servable txsb5-1-billowing-dragon is in invalid state: Ping timeout exceeded. Info: Ping error: UNIMPLEMENTED: Method not found!

## Description

I upload my model successed, then add new application on web UI but show the error message above.

hydro version: 2.1.0

## Container log

```shell
INFO:main:Reading the model...
INFO:main:Runtime is ready to serve...
INFO:main:Starting server on [::]:9091
```

File tree in container:
```
- /model
  - contract.protobin
  - files/
    - model.h5
    - requirements.txt
    - serving.yaml
    - src/
       - func_main.py
```

**Comment by KineticCookie** [comment]
Hi @archichen 
Seems like you use an old runtime without healthchecks 🤔 
Can you please specify what runtime do you use for your model?
