### ISSUE TITLE
How to use external docker registry

### ISSUE THREAD

**Issue by cernard** [Hydrospheredata/hydro-serving#338]
I already have a docker registry (harbor), so how I use external docker registry in hydro which deployed on k8s.

**Comment by tidylobster** [comment]
Hi @cernard, you can refer to the documentation here: https://docs.hydrosphere.io/v/master/quickstart/installation/configuring-helm-charts

If you have any further questions, please, join our slack workspace and ask there. https://hydrospheredata.slack.com/

Closing this issue, as it doesn't state any problem.
