### ISSUE TITLE
Model container has conflicting name after db cleanup

### ISSUE THREAD

**Issue by dos65** [Hydrospheredata/hydro-serving#39]
Steps to reproduce:
- start manager and deploy some model
- restart manager with empty db
- try to deploy same model as on first step

```
com.spotify.docker.client.exceptions.DockerRequestException:
  Request error: POST unix://localhost:80/containers/create?name=binarizer_0-0-1: 409,
  body: {"message":"Conflict. The container name \"/binarizer_0-0-1\" is already in use by container \"d60aff912cdce7106249b7fc1d8b5707c398492bd3027d255bfae372bcab851e\".
  You have to remove (or rename) that container to be able to reuse that name."}
```

**Comment by KineticCookie** [comment]
db wipe is considered as critical failure and it requires infrastructure cleanup, since majority of metadata about model versions and services is lost

however manager should somehow handle conflicting container names

finally, this issue is merged as part of #70
