### ISSUE TITLE
Cant start Gateway

### ISSUE THREAD

**Issue by tylerfordML** [Hydrospheredata/hydro-serving#57]
I get this error over and over when trying to start the gateway service. 

018-01-22T05:45:32.966950578Z [ERROR] io.hydrosphere.serving.gateway.actor.PipelineSynchronizeActor Unsupported Content-Type, supported: application/json WARNING arguments left: 1

**Comment by Zajs** [comment]
@tylerfordML Could you please provide more details:
1. Where do you start serving cluster? Is it local environment? Or Amazon ECS? Or another one?
2. Is it your production environment? If no, you can use the manager instance without the gateway. They both have same functionality related to serving models.
3. Which version of serving do you use? If it from the master branch, it won't work. Please use code from release tags.

**Comment by tylerfordML** [comment]
I am running it locally. I am doing a checkout from branch / tag 0.0.18.

**Comment by Zajs** [comment]
I see.  
For now, it will be better to avoid gateway usage. You can use our UI (https://github.com/Hydrospheredata/hydro-serving-ui). Small instruction:
#### Clone repositories

```
#Sidecar + manager + gateway + dummy runtime 
git clone https://github.com/Hydrospheredata/hydro-serving
#ML Runtimes + ML models repository
git clone https://github.com/Hydrospheredata/hydro-serving-runtime
```
#### Build modules 
Change directory to `hydro-serving` and:
```
sbt compile docker
```
Change directory to `hydro-serving-runtime` and:
```
./build.sh
```
##### Without Docker-Compose
* Run database
```
docker run -e POSTGRES_DB=docker \
    -e POSTGRES_USER=docker \
    -e POSTGRES_PASSWORD=docker \
    -p 5432:5432 \
    postgres:9.6-alpine
```
* Run manager
```
export HOST_IP=$(ifconfig en0 | grep 'inet ' |  awk '{ print $2}')
export MODEL_DIRECTORY=/path/to/hydro-serving-runtime/models
docker run -e ADVERTISED_MANAGER_HOST=$HOST_IP \
    -e DATABASE_HOST=$HOST_IP \
    -e ZIPKIN_ENABLED=true \
    -e ZIPKIN_HOST=$HOST_IP \
    -p 8080:8080 -p 8082:8082 -p 9090:9090 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v ${MODEL_DIRECTORY}:/models \
    hydrosphere/serving-manager:0.0.1
```
* Run UI
```
HOST_IP=$(ifconfig en0 | grep 'inet ' |  awk '{ print $2}')
docker run -e MANAGER_HOST=$HOST_IP:8080 -p 9192:80 \
    hydrosphere/serving-manager-ui:0.0.17
```
### Available Resources
* jdbc:postgresql://localhost:5432/docker - Postgresql
* http://localhost:8080/swagger/swagger-ui.html - Manager
* http://localhost:9192 - UI

Sorry for the lack of documentation.

**Comment by tylerfordML** [comment]
its not seeing any of the models now.

**Comment by Zajs** [comment]
Could you provide some logs?
