### ISSUE TITLE
Vectors are returning blank

### ISSUE THREAD

**Issue by tylerfordML** [Hydrospheredata/hydro-serving#69]
Using the 0.0.18 release and vectors come back blank. tfidf and cv_tf should both return vectors. 

[
  {
    "filtered": [
      "foo"
    ],
    "UU_EVAL_RESP_FTEXT": "foo",
    "tfiddf": [],
    "cv_tf": [],
    "tokens": [
      "foo"
    ]
  }
]

**Comment by KineticCookie** [comment]
Hello @tylerfordML 
Could you please specify:
1. RuntimeType (e.g. hydrosphere/spark-local-2.1:0.0.1)
2. What library did you use to train a model?

**Comment by KineticCookie** [comment]
closed since runtimes were revamped
