### ISSUE TITLE
Problems with docker-compose

### ISSUE THREAD

**Issue by Tereshin** [Hydrospheredata/hydro-serving#85]
https://pastebin.com/UbaqEsjJ

**Comment by KineticCookie** [comment]
@Zajs in some cases there are problems with discovering a manager.
@IceKhan13 encountered the same error and wasn't able to access a manager.

**Comment by KineticCookie** [comment]
Seems like 029447584fb3d0e48ee8481ec31559a8a22d6475 fixes the issue. I need a feedback from you guys to be sure.

**Comment by KineticCookie** [comment]
Bug still happens.
I assume that sidecar can't establish a handshake with manager, because it initialized later on. I added a sleep (3c683f96d954ea5cf487c810c22817b0564af13a) to be sure that manager will be initialized before sidecar.
