### ISSUE TITLE
Issue with docker compose.

### ISSUE THREAD

**Issue by tylerfordML** [Hydrospheredata/hydro-serving#93]
I am using the latest code. 

manager     | [ERROR] i.h.s.m.ManagerHttpApi i.h.s.m.ManagerHttpApi$$anonfun$1.applyOrElse.76 null
manager     | java.lang.RuntimeException: null
manager     | 	at io.hydrosphere.serving.manager.service.prometheus.PrometheusMetricsServiceImpl.fetchServices(PrometheusMetricsService.scala:37) ~[manager.jar:latest]
manager     | 	at io.hydrosphere.serving.manager.controller.prometheus.PrometheusMetricsController$$anonfun$getServices$1$$anonfun$apply$1$$anonfun$apply$2.apply(PrometheusMetricsController.scala:30) ~[manager.jar:latest]
manager     | 	at io.hydrosphere.serving.manager.controller.prometheus.PrometheusMetricsController$$anonfun$getServices$1$$anonfun$apply$1$$anonfun$apply$2.apply(PrometheusMetricsController.scala:30) ~[manager.jar:latest]

sidecar     | [2018-02-09 02:03:07.572][26][debug][main] source/server/connection_handler_impl.cc:129] [C10] new connection
sidecar     | [2018-02-09 02:03:07.572][26][debug][http] source/common/http/conn_manager_impl.cc:181] [C10] new stream
sidecar     | [2018-02-09 02:03:07.572][26][debug][http] source/common/http/conn_manager_impl.cc:439] [C10][S4601685897479926094] request headers complete (end_stream=true):
sidecar     | [2018-02-09 02:03:07.572][26][debug][http] source/common/http/conn_manager_impl.cc:444] [C10][S4601685897479926094]   ':authority':'hd-nd05.campus.utah.edu:8080'
sidecar     | [2018-02-09 02:03:07.572][26][debug][http] source/common/http/conn_manager_impl.cc:444] [C10][S4601685897479926094]   'user-agent':'curl/7.52.1'
sidecar     | [2018-02-09 02:03:07.572][26][debug][http] source/common/http/conn_manager_impl.cc:444] [C10][S4601685897479926094]   'accept':'*/*'
sidecar     | [2018-02-09 02:03:07.572][26][debug][http] source/common/http/conn_manager_impl.cc:444] [C10][S4601685897479926094]   ':path':'/v1/prometheus/services'
sidecar     | [2018-02-09 02:03:07.572][26][debug][http] source/common/http/conn_manager_impl.cc:444] [C10][S4601685897479926094]   ':method':'GET'
sidecar     | [2018-02-09 02:03:07.572][26][debug][router] source/common/router/router.cc:239] [C10][S4601685897479926094] cluster 'manager-http' match for URL '/v1/prometheus/services'
sidecar     | [2018-02-09 02:03:07.572][26][debug][router] source/common/router/router.cc:284] [C10][S4601685897479926094]   ':authority':'hd-nd05.campus.utah.edu:8080'
sidecar     | [2018-02-09 02:03:07.572][26][debug][router] source/common/router/router.cc:284] [C10][S4601685897479926094]   'user-agent':'curl/7.52.1'
sidecar     | [2018-02-09 02:03:07.572][26][debug][router] source/common/router/router.cc:284] [C10][S4601685897479926094]   'accept':'*/*'
sidecar     | [2018-02-09 02:03:07.572][26][debug][router] source/common/router/router.cc:284] [C10][S4601685897479926094]   ':path':'/v1/prometheus/services'
sidecar     | [2018-02-09 02:03:07.572][26][debug][router] source/common/router/router.cc:284] [C10][S4601685897479926094]   ':method':'GET'
sidecar     | [2018-02-09 02:03:07.572][26][debug][router] source/common/router/router.cc:284] [C10][S4601685897479926094]   'x-forwarded-proto':'http'
sidecar     | [2018-02-09 02:03:07.572][26][debug][router] source/common/router/router.cc:284] [C10][S4601685897479926094]   'x-request-id':'35b54b31-9920-9176-9df7-30d0d1c3fc1e'
sidecar     | [2018-02-09 02:03:07.572][26][debug][router] source/common/router/router.cc:284] [C10][S4601685897479926094]   'x-b3-traceid':'8e19a689e87492a5'
sidecar     | [2018-02-09 02:03:07.572][26][debug][router] source/common/router/router.cc:284] [C10][S4601685897479926094]   'x-b3-spanid':'8e19a689e87492a5'
sidecar     | [2018-02-09 02:03:07.572][26][debug][router] source/common/router/router.cc:284] [C10][S4601685897479926094]   'x-b3-sampled':'1'
sidecar     | [2018-02-09 02:03:07.572][26][debug][router] source/common/router/router.cc:284] [C10][S4601685897479926094]   'x-ot-span-context':'8e19a689e87492a5;8e19a689e87492a5;0000000000000000'
sidecar     | [2018-02-09 02:03:07.572][26][debug][router] source/common/router/router.cc:284] [C10][S4601685897479926094]   'x-envoy-expected-rq-timeout-ms':'15000'
sidecar     | [2018-02-09 02:03:07.572][26][debug][router] source/common/router/router.cc:284] [C10][S4601685897479926094]   ':scheme':'http'
sidecar     | [2018-02-09 02:03:07.572][26][debug][pool] source/common/http/http1/conn_pool.cc:74] [C3] using existing connection
sidecar     | [2018-02-09 02:03:07.572][26][debug][router] source/common/router/router.cc:902] [C10][S4601685897479926094] pool ready
sidecar     | [2018-02-09 02:03:07.575][26][debug][router] source/common/router/router.cc:553] [C10][S4601685897479926094] upstream headers complete: end_stream=false
sidecar     | [2018-02-09 02:03:07.575][26][debug][http] source/common/http/conn_manager_impl.cc:859] [C10][S4601685897479926094] encoding headers via codec (end_stream=false):
sidecar     | [2018-02-09 02:03:07.575][26][debug][http] source/common/http/conn_manager_impl.cc:864] [C10][S4601685897479926094]   'server':'envoy'
sidecar     | [2018-02-09 02:03:07.575][26][debug][http] source/common/http/conn_manager_impl.cc:864] [C10][S4601685897479926094]   'date':'Fri, 09 Feb 2018 02:03:07 GMT'
sidecar     | [2018-02-09 02:03:07.575][26][debug][http] source/common/http/conn_manager_impl.cc:864] [C10][S4601685897479926094]   'content-type':'text/plain; charset=UTF-8'
sidecar     | [2018-02-09 02:03:07.575][26][debug][http] source/common/http/conn_manager_impl.cc:864] [C10][S4601685897479926094]   'content-length':'13'
sidecar     | [2018-02-09 02:03:07.575][26][debug][http] source/common/http/conn_manager_impl.cc:864] [C10][S4601685897479926094]   ':status':'500'
sidecar     | [2018-02-09 02:03:07.575][26][debug][http] source/common/http/conn_manager_impl.cc:864] [C10][S4601685897479926094]   'x-envoy-upstream-service-time':'2'

**Comment by Zajs** [comment]
We didn't have implementation for Prometheus in new version. Added implementation in #106.
Now you can use Prometheus to fetch metrics from model runtimes.
#####  Build docker with `Prometheus`
```
docker build --no-cache -t hydro-serving/prometheus integrations/automation/prometheus
```

##### Start `Prometheus`
```
export HOST_IP=$(ifconfig en0 | grep 'inet ' |  awk '{ print $2}')
docker run -p 9093:9090 -e MANAGER_HOST=$HOST_IP -e MANAGER_PORT=8080 hydro-serving/prometheus:latest
```
http://localhost:9093/graph?g0.range_input=1h&g0.expr=envoy_cluster_version&g0.tab=0 - Prometheus UI. List of available metrics can be found [here](https://www.envoyproxy.io/docs/envoy/v1.5.0/configuration/cluster_manager/cluster_stats.html#config-cluster-manager-cluster-stats) 

##### Start `Grafana`
```
docker run -p 3000:3000 -e GF_SECURITY_ADMIN_PASSWORD=foobar -e GF_USERS_ALLOW_SIGN_UP=false grafana/grafana:4.6.3
```

##### Add `Prometheus` as Source to `Grafana`
```
export HOST_IP=$(ifconfig en0 | grep 'inet ' |  awk '{ print $2}')
curl --header 'Content-Type: application/json' --header 'Accept: */*' \
-X POST http://admin:foobar@$HOST_IP:3000/api/datasources \
-d @- << EOF
{
  "Name": "Prometheus",
  "Type": "prometheus",
  "url": "http://$HOST_IP:9093",
  "Access": "proxy",
  "isDefault": true
}
EOF
```

##### Add new Dashboard to `Grafana`
```
export HOST_IP=$(ifconfig en0 | grep 'inet ' |  awk '{ print $2}')
curl --header 'Content-Type: application/json' \
 --header 'Accept: */*' \
 -X POST http://admin:foobar@$HOST_IP:3000/api/dashboards/db \
 --data-binary @./integrations/automation/grafana/local/models.json
```

##### Open new [Dashboard http://localhost:3000/dashboard/db/simple-models](http://localhost:3000/dashboard/db/simple-models)
